# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7e3ae6e34a88c44ba2d7e585c9bee348541028e8fb4b87d6cbf05e5dd394d5f957afba8daef0c555dc53331dcd00c78546d923ce1a0899cdd06cc6191aa40dd6

test:
  secret_key_base: 5e221d347f90f526c2f2b0c7d81bbd7e2c51af22f6da2d4298d99964beb8ebd4183667c983eec9d403b4c223b7065c866ed89a017b278477d8818197ddfdc103

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
